[window]

dimensions = { columns = 120, lines = 32 }
padding = { x = 10, y= 10 }
opacity = 0.75

[terminal]

shell = "/usr/bin/zsh"

[font]

normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }

size = 12

